#################################
#            xD-Bans            #
#          Autor xDGWG          #
#        https://xdgwg.pl       #
#################################


configs:
  #flat albo mysql
  dataType: flat

#Sprawdzanie poprawności wielkich liter w nazwie gracza
  playerNameFilter: true

#Liczba ostrzeżeń po której wykonywana jest komenda
  warningsCount: 3

#Komenda, która jest wykonywana po osiągnięciu przez gracza maksymalnej liczby ostrzeżeń
  warningsCommand: "/tempban {PLAYER} 7 d Zebranie trzech ostrzezen!"

#Jeżeli "dataType: mysql" wypełnij to
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "pass"
    name: "xD-Bans"

messages:
  noPermission: "&4Blad: &cNie masz dostepu do tej komendy! &8(&7{PERM}&8)"

  usage: "&4Blad: &cPoprawne uzycie: &7{USAGE}"

  notExist: "&4Blad: &cPodany gracz nie istnieje!"

  bypass: "&4Blad: &cPodany gracz jest nietykalny!"

  banned: "&4Blad: &cPodany gracz jest juz zbanowany!"

  notBanned: "&4Blad: &cPodany gracz nie jest zbanowany!"

  banBroadcast: "&8>> &cGracz &4{PLAYER} &czostal zbanowany przez &4{ADMIN} &cza &4{REASON}&c!"

  unbanBroadcast: "&8>> &aGracz &2{PLAYER} &azostal odbanowany przez &2{ADMIN}&a!"

  banYourself: "&4Blad: &cNie mozesz siebie zbanowac!"

  bypassOn: "&8>> &cOd teraz gracz &4{PLAYER} &cjest nietykalny!"

  bypassOff: "&8>> &cOd teraz gracz &4{PLAYER} &cjest tykalny!"

  badNickname: "&8&l>> &cWejdz na serwer za pomoca nazwy &4{NORMAL-NAME} &ca nie &4{NAME}&c!"

  tempBanBroadcast: "&8>> &cGracz &4{PLAYER} &czostal zbanowany przez &4{ADMIN} &cza &4{REASON} &cna &4{TIME}&c!"

  kickPlayerBroadcast: "&8>> &cGracz &4{PLAYER} &czostal wyrzucony z serwera przez &4{ADMIN} &cza &4{REASON}&c!"

  kickAllBroadcast: "&8>> &cWszyscy gracze zostali wyrzuceni z serwera przez &4{ADMIN} &cza &4{REASON}&c!"

  muteBroadcast: "&8>> &cGracz &4{PLAYER} &czostal wyciszony przez &4{ADMIN} &cza &4{REASON}&c!"

  muted: "&4Blad: &cPodany gracz jest juz wyciszony!"

  muteMessage: "&4Blad: &cJestes wycisozny przez &4{ADMIN} &cza &4{REASON}&c!"

  muteYourself: "&4Blad: &cNie mozesz siebie wyciszyc!"

  notMuted: "&4Blad: &cPodany gracz nie jest wyciszony!"

  unmuteBroadcast: "&8>> &aGracz &2{PLAYER} &amoze znowu pisac na chacie!"

  tempMuteBroadcast: "&8>> &cGracz &4{PLAYER} &czostal wyciszony przez &4{ADMIN} &cza &4{REASON} &cna &4{TIME}&c!"

  tempMuteMessage: "&4Blad: &cJestes wyciszony przez &4{ADMIN} &cna &4{TIME} &cza &4{REASON}"

  warnBroadcast: "&8>> &cGracz &4{PLAYER} &cotrzymał &4ostrzezenie &cod &4{ADMIN} &cza &4{REASON}&c! &8(&c{WARNINGS}&7/&4{MAX}&8)"

  warnYourself: "&4Blad: &cNie mozesz dac sobie ostrzezenia!"

  warnBannedPlayer: "&4Blad: &cNie mozesz dac ostrzezenia zbanowanemu graczowi!"

  banList: "&8>> &cLista zbanowanych graczy: &7{LIST}"

  muteList: "&8>> &cLista wyciszonych graczy: &7{LIST}"

  bypassList: "&8>> &cLista nietykalnych graczy: &7{LIST}"

  timeFormat:
    seconds: "sek."
    minutes: "min."
    hours: "godz."
    days: "dni"

  kick:
    - "&8<==============================>"
    - "&4Zostales wyrzucony z serwera!"
    - ""
    - "&8>> &cPowod: &7{REASON}"
    - "&8>> &cWyrzucajacy: &7{ADMIN}"
    - "&8<==============================>"

  banKick:
    - "&8<==============================>"
    - "&4Zostales zbanowany!"
    - ""
    - "&8>> &cPowod: &7{REASON}"
    - "&8>> &cBanujacy: &7{ADMIN}"
    - "&8<==============================>"

  tempBanKick:
    - "&8<==============================>"
    - "&4Zostales tymczasowo zbanowany!"
    - ""
    - "&8>> &cPowod: &7{REASON}"
    - "&8>> &cBanujacy: &7{ADMIN}"
    - "&8>> &cUnban za: {TIME}"
    - "&8<==============================>"

  banJoin:
    - "&8<==============================>"
    - "&4Zostales zbanowany!"
    - ""
    - "&8>> &cPowod: &7{REASON}"
    - "&8>> &cBanujacy: &7{ADMIN}"
    - "&8<==============================>"

  tempBanJoin:
    - "&8<==============================>"
    - "&4Zostales tymczasowo zbanowany!"
    - ""
    - "&8>> &cPowod: &7{REASON}"
    - "&8>> &cBanujacy: &7{ADMIN}"
    - "&8>> &cUnban za: {TIME}"
    - "&8<==============================>"

  check:
    lines:
      - "&8-------------------------------------"
      - "&8>> &7Gracz: &c{PLAYER}"
      - "&8>> &7Uuid: &c{UUID}"
      - "&8>> &7Ip: &c{IP}"
      - "&8>> &7Mozna zbanowac: &c{BYPASS}"
      - "&8>> &7Liczba ostrzezen: &c{WARNINGS}"
      - "&8>> &7Rodzaj bana: &c{BAN-STATUS}"
      - "&8>> &7Czas bana: &c{BAN-TIME}"
      - "&8>> &7Powod bana: &c{BAN-REASON}"
      - "&8>> &7Zbanowal: &c{BAN-ADMIN}"
      - "&8>> &7Wyciszony: &c{MUTE-STATUS}"
      - "&8>> &7Czas wyciszenia: &c{MUTE-TIME}"
      - "&8>> &7Powod wyciszenia: &c{MUTE-REASON}"
      - "&8>> &7Wyciszyl: &c{MUTE-ADMIN}"
      - "&8-------------------------------------"
    banStatus:
      noBan: "-"
      permBan: "Permanentny"
      tempBan: "Tymczasowy"
    muteStatus:
      noMute: "Nie"
      permMute: "Permanentnie"
      tempMute: "Tymczasowo"
    bypass:
      enable: "Tak"
      disable: "Nie"